Ansible 4
Otus-DevOps-2017-11/epanoff_infra pull request #10
Opened 2018-02-03 22:07 UTC by epanoff

Homework 13
ansible

Создан Vagrantfile
Добавлен base.yml
Доработаны роли app и db
Конфигурация проверена
nginx под вагрантом настроил при помощи ansible.extra_vars = { "deploy_user" => "ubuntu", "nginx_sites" => { "default": ["listen 80", "server_name "reddit"", "location / { proxy_pass http://127.0.0.1:9292; }"]} } end
Добавлено тестирование db
В пакеры вместо плейбуков роли с тегами
*
Вынес db в https://github.com/epanoff/infra-db-ansible
Добавил travis-ci (часов пять ушло)
Настроил оповещения по аналогии с 4 заданием

2018-02-06 11:21 UTC, Nklya requested changes
Добрый день.

Егор, базовое задание относительно нормальное.

Нужно:
1. Плейбуки пакера вернуть в playbooks.
2. Роль db нужно было вынести из этой репы. Можно ее переименовать в db_old
3. В роль https://github.com/epanoff/infra-db-ansible закоммичены логи и *.pyc файлы. Их нужно вычистить
4. В репу закоммичен мусор `ansible/roles/db/molecule/default/.pytest_cache/v/cache/lastfailed`. Нужно вычистить
5. В куче файлов нет последней пустой строки. Настрой пожалуйста свой редактор на добавление при сохранении.

2018-02-06 11:21 UTC, Nklya commented on packer/app.json
> +            "playbook_file": "ansible/old/packer_app.yml",
Плейбуки пакера должны быть в ansible/playbooks

2018-02-06 11:21 UTC, Nklya commented on packer/db.json
> +            "playbook_file": "ansible/old/packer_db.yml",
Плейбуки пакера должны быть в ansible/playbooks

2018-02-06 11:21 UTC, Nklya commented on .gitignore
> +# http://iamzed.com/2009/05/07/a-primer-on-virtualenv/
Это что в гитигноре?

2018-02-06 11:21 UTC, Nklya commented on ansible/playbooks/deploy.yml
> +  become: true
И зачем здесь become?

2018-02-06 11:21 UTC, Nklya commented on terraform/modules/app/main.tf
> +    ports    = ["9292", "80"]
Стоило отдельный ресурс под это запилить

2018-02-06 11:22 UTC, Nklya commented
У тебя кругом гитхаб даже показывает отсутсвие пустых линий в конце файлов
<img width="387" alt="screen shot 2018-02-06 at 14 22 04" src="https://user-images.githubusercontent.com/26086394/35857117-321a7f6e-0b49-11e8-9c21-6be4c3426fce.png">

2018-02-06 17:36 UTC, epanoff commented on ansible/playbooks/deploy.yml
> +  become: true
Убрал

2018-02-06 17:37 UTC, epanoff commented on terraform/modules/app/main.tf
> +    ports    = ["9292", "80"]
Сделал.

2018-02-08 10:38 UTC, Nklya requested changes
Добрый день.

Проблемы, которые нужно исправить:
1. В плейбуках пакера в этом дз мы переходим на использование ролей.
2. Из роли не вычищен мусор (pyc, log) https://github.com/epanoff/infra-db-ansible/
3. В requirements stage нет db роли

2018-02-08 10:38 UTC, Nklya commented on ansible/environments/stage/requirements.yml
> +- src: https://github.com/bennojoy/nginx
В stage db роль уже не нужна?

2018-02-14 11:40 UTC, Nklya approved these changes
Добрый день.

Теперь все ок.

2018-02-14 11:59 UTC, merged