Packer base
Otus-DevOps-2017-11/epanoff_infra pull request #3
Opened 2017-12-27 22:09 UTC by epanoff

homework 7

2017-12-28 14:19 UTC, vitkhab requested changes
Молодец, что решил попробовать выполнить доп задания. Но требуются доработки:
- привести в порядок `variables.json.example`
- внести в `.gitignore` *.swp файлы
- убрать дубли скриптов
- Обеспечить автостарт сервиса в образе `reddit-full`

Все ли понятно? Нужна ли помощь?

2017-12-28 14:19 UTC, vitkhab commented on packer/variables.json.example
> +    "proj_id": infra,
Не хватает кавычек

2017-12-28 14:19 UTC, vitkhab commented on packer/variables.json.example
> +    "source_image_family": ubuntu-1604-lts
А тут еще и запятой в конце строки

2017-12-28 14:19 UTC, vitkhab commented on packer/files/install_mongodb.sh
> +#!/bin/bash
А зачем ты дублируешь скрипты установки mongo и ruby в директриях scripts и files?

2017-12-28 14:19 UTC, vitkhab commented on packer/files/install_mongodb.sh
> +sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
Использовать sudo в скриптах не обязательно, так как packer в твоей конфигурации уже вызывает скрипты через sudo

2017-12-28 14:19 UTC, vitkhab commented on packer/immutable.json
> +    "startup_script_file": "files/deploy.sh"
Этот скрипт вызывается один раз при создании образа. При запуске ВМ из образа скрипт не запускается.
https://www.packer.io/docs/builders/googlecompute.html#startup-scripts

2017-12-28 14:19 UTC, vitkhab commented on packer/files/deploy.sh
> +ps aux | grep puma
Автостарт сервиса надо реализовать каким-то другим способом.

2017-12-28 14:43 UTC, epanoff commented on packer/files/install_mongodb.sh
> +#!/bin/bash
По тексту задания было, что для full образа файлы должны быть в files, а для base образа в папке scripts.

2017-12-28 14:43 UTC, epanoff commented on packer/immutable.json
> +    "startup_script_file": "files/deploy.sh"
Да знаю.

2017-12-28 14:44 UTC, epanoff commented on packer/variables.json.example
> +    "proj_id": infra,
Поправлю.

2017-12-28 14:44 UTC, epanoff commented on packer/variables.json.example
> +    "source_image_family": ubuntu-1604-lts
Поправлю.

2017-12-28 14:44 UTC, epanoff commented on packer/files/install_mongodb.sh
> +sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
Уберу sudo

2017-12-28 14:46 UTC, epanoff commented on packer/files/deploy.sh
> +ps aux | grep puma
А можешь намекнуть? Я реализовал автостарт при помощи startup-script в create-reddit-vm.sh

2017-12-29 13:43 UTC, Nklya commented on packer/files/deploy.sh
> +ps aux | grep puma
Посмотри следующее ДЗ, там рассматривается systemd unit для запуска puma.

2018-01-09 09:31 UTC, vitkhab approved these changes
Технически все прекрасно. Так держать!
Оба дополнительных задания выполнены. Молодец!

Дополнительные правки на твое усмотрение, работа зачтена.

2018-01-09 09:31 UTC, vitkhab commented on packer/immutable.json
> +    "startup_script_file": "scripts/deploy.sh"
Строчка лишняя
Данная инструкция выполняется при запуске VM при подготовке образа. Скрипт при запуске VM из образа запускаться не будет.

2018-01-09 09:31 UTC, vitkhab commented on README.md
> +Создание fry, bakes образов при помощи packer.
Хотелось бы побольше документации. Пример, куда можно стремиться https://goo.gl/me4MEX

2018-01-10 17:26 UTC, merged