homework-09
Otus-DevOps-2017-11/epanoff_infra pull request #6
Opened 2018-01-21 21:39 UTC by epanoff

# Homework 9

Добавил resource "google_compute_firewall" "firewall_ssh"
Импортивал google_compute_firewall.firewall_ssh default-allow-ssh
Добавил google_compute_address. Привязал их к app инстансам.  В процессе наткнулся на то что в прошлом задании у меня уже было два инстанса плюс балансировщик и уперся в лимиты
Поэтому отказался от второго инстанса и балансивщика. (Потом в задании есть требования удалить лишние сущиности)
Скопировал файл ubuntu16.json в app.json и db.json. Удалил лишнее и добавил в название app и db соответсвенно
Создал на основа app.json и db.json новые образы пакером.
Создал и проверил разбиение на app и db сервер.
Переместил новые app.tf и db.tf в новые модули.
Разделил среды на prod и на stage с разным доступом.
# *
state файл сделал на GCS при помощи файла backend.tf
Если запустить одновременно apply то во втором случае будет ошибка вида
Error loading state: writing "gs://infra-189214/terraform.tflock" failed
значит работает
# *
Добавил провижионер для app. Для бд не нужно там и так mongodb в автозагрузке
Но понять почему puma не видит БД так и не смог. Наверное что-то упустил.

2018-01-22 18:44 UTC, Nklya requested changes
Добрый вечер.

Егор, в принципе почти все ок.

Кроме закомиченых стейтов terraform.tfstate.txt и 
terraform.tfstate.backup.txt

Их нужно вычистить из репы.

Ну и по поводу монги я ниже написал.

2018-01-22 18:44 UTC, Nklya commented on terraform/variables.tf
> +
Зачем в terraform/variables.tf все эти переменные, если по факту используются только 
+  project = "${var.project}"
 +  region  = "${var.region}"

2018-01-22 18:44 UTC, Nklya commented on terraform/stage/backend.tf
> +    project = "infra-189214"
проект не обязательно здесь указывать

2018-01-22 18:44 UTC, Nklya commented on terraform/stage/backend.tf
> +    bucket  = "infra-189214"
Не обязательно бакет называть именем проекта.

2018-01-22 18:44 UTC, Nklya commented on README.md
> +Но понять почему puma не видит БД так и не смог. Наверное что-то упустил.
Потому что нужно настраивать конфиг монги, чтобы она слушала не только на локалхосте.
Посмотри ДЗ 11.

2018-01-27 08:22 UTC, epanoff commented on terraform/variables.tf
> +
Почистил лишнее

2018-01-27 08:23 UTC, epanoff commented on terraform/stage/backend.tf
> +    project = "infra-189214"
Переделал

2018-01-27 08:23 UTC, epanoff commented on terraform/stage/backend.tf
> +    bucket  = "infra-189214"
Переделал

2018-01-27 08:23 UTC, epanoff commented on README.md
> +Но понять почему puma не видит БД так и не смог. Наверное что-то упустил.
Прошелся sed-ом по конфигу монги, рестартанул

2018-01-29 15:43 UTC, Nklya approved these changes
Да, теперь все ок.

2018-01-29 15:43 UTC, Nklya commented on terraform/modules/db/main.tf
> +      "sudo sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf",
Не сказал бы, что это хорошая практика седом фигачить. Можно было шаблон рендерить, как для приложения.
Мы дальше ансиблом будем будем из шаблона.

2018-01-29 15:58 UTC, merged

2018-01-29 15:58 UTC, Nklya commented
Мержим, потому что мешает проверять дальше.